# Copyright 2017-2019 Hans Dembinski
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

shallow_clone: true

image: Visual Studio 2017

build: off

branches:
  only:
    - master
    - develop

install:
  # Cloning minimal set of Boost libraries
  - cd ..
  - git clone -b master --depth 10 https://github.com/boostorg/boost.git
  - cd boost
  - git submodule update --init --depth 10 tools/build tools/boostdep

  # Replacing Boost module with this project and installing Boost dependencies
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\histogram\
  - python tools\boostdep\depinst\depinst.py --git_args "--depth 10 --jobs 2" histogram

  # Adding missing toolsets and preparing Boost headers
  - cmd /c bootstrap
  - b2 headers

test_script:
  - b2 -j2 -q libs\histogram\test

on_failure:
  # Stop VM and enable interactive login
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
